/**
 * Domain model for Iurify Case.
 *
 * Source of truth: docs/modelo de datos.png (class diagram).
 * Entity and field names intentionally match the backend (Spring Boot) model so
 * that JSON payloads can be consumed without renaming. Do not translate or
 * rename these fields in the frontend.
 *
 * Nullability follows the diagram: only fields explicitly marked as optional
 * there (e.g. AlertaAuditoria.nodoRelacionadoId) are typed as nullable.
 */

/** UUID serialized as a string. */
export type UUID = string;

/** Java LocalDateTime serialized as an ISO-8601 string (e.g. "2026-10-05T10:45:00"). */
export type ISODateTime = string;

// ---------------------------------------------------------------------------
// Autenticación (FR-008)
// ---------------------------------------------------------------------------

export type RolUsuario = 'Abogado' | 'Asistente';

/**
 * Usuario as exposed to the client.
 * `passwordHash` exists in the backend model but must never reach the frontend,
 * so it is deliberately omitted here.
 */
export interface Usuario {
  id: UUID;
  nombre: string;
  email: string;
  fechaRegistro: ISODateTime;
  rol: RolUsuario;
}

// ---------------------------------------------------------------------------
// Gestión Jurídica (FR-007)
// ---------------------------------------------------------------------------

export type EstadoExpediente = 'Abierto' | 'En_Auditoria' | 'Cerrado';

export interface Expediente {
  id: UUID;
  usuarioId: UUID;
  titulo: string;
  descripcionBreve: string;
  fechaCreacion: ISODateTime;
  fechaActualizacion: ISODateTime;
  estado: EstadoExpediente;
}

/** Generated by FR-005 / FR-006. */
export type TipoDocumento = 'ALEGATO' | 'MINUTA' | 'CONCEPTO';

export interface DocumentoLegal {
  id: UUID;
  expedienteId: UUID;
  contenidoHtml: string;
  urlPdf: string;
  fechaGeneracion: ISODateTime;
  tipoDocumento: TipoDocumento;
}

// ---------------------------------------------------------------------------
// Ingesta Conversacional IA (FR-001)
// ---------------------------------------------------------------------------

export interface SesionConversacion {
  id: UUID;
  expedienteId: UUID;
  fechaInicio: ISODateTime;
  activa: boolean;
}

export type RemitenteMensaje = 'USUARIO' | 'IA';
export type TipoContenidoMensaje = 'TEXTO' | 'AUDIO';

export interface Mensaje {
  id: UUID;
  sesionId: UUID;
  contenido: string;
  audioUrl: string;
  timestamp: ISODateTime;
  remitente: RemitenteMensaje;
  tipoContenido: TipoContenidoMensaje;
}

// ---------------------------------------------------------------------------
// Auditoría IA (FR-004)
// ---------------------------------------------------------------------------

export type NivelRiesgo = 'BAJO' | 'MEDIO' | 'ALTO';

export interface AuditoriaProcesal {
  id: UUID;
  expedienteId: UUID;
  fechaAnalisis: ISODateTime;
  nivelRiesgoGlobal: NivelRiesgo;
}

export type TipoAlerta = 'VACIO_PROCESAL' | 'CONTRADICCION' | 'DEBILIDAD';
export type SeveridadAlerta = 'CRITICA' | 'ADVERTENCIA' | 'SUGERENCIA';

export interface AlertaAuditoria {
  id: UUID;
  auditoriaId: UUID;
  descripcion: string;
  /** Optional in the model: the canvas node the alert points at (señala_error_en). */
  nodoRelacionadoId: UUID | null;
  tipo: TipoAlerta;
  severidad: SeveridadAlerta;
}

// ---------------------------------------------------------------------------
// Lienzo Visual y Grafo (FR-002, FR-003)
// ---------------------------------------------------------------------------

export interface Lienzo {
  id: UUID;
  expedienteId: UUID;
  version: number;
  ultimaModificacion: ISODateTime;
}

export type TipoNodo = 'HECHO' | 'PRUEBA' | 'LEY' | 'JURISPRUDENCIA';

export interface NodoLienzo {
  id: UUID;
  lienzoId: UUID;
  titulo: string;
  descripcion: string;
  posicionX: number;
  posicionY: number;
  tipo: TipoNodo;
}

export type TipoRelacion = 'RESPALDA' | 'CONTRADICE' | 'VINCULA';

export interface EnlaceLienzo {
  id: UUID;
  lienzoId: UUID;
  nodoOrigenId: UUID;
  nodoDestinoId: UUID;
  tipoRelacion: TipoRelacion;
}
